plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.11-SNAPSHOT" apply false
    id "com.gradleup.shadow" version "8.3.6" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}


subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "com.github.johnrengelman.shadow"

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

        mappings loom.layered() {

            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.parchment_version}")
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    archivesBaseName = rootProject.mod_id
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {

        flatDir {
            dirs 'mods'
        }

        mavenLocal()

        maven { url "https://maven.parchmentmc.org" }

        exclusiveContent {
            forRepository {
                maven {
                    name = "CurseForge"
                    url = "https://www.cursemaven.com"
                }
            }
            filter {
                includeGroup "curse.maven"
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/releases"
        }
        maven {
            name = "MehVadJukaar"
            url = "https://registry.somethingcatchy.net/repository/maven-releases/"
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Gegy"
                    url = "https://maven.gegy.dev"
                }
            }
            filter {
                includeGroupAndSubgroups("dev.lambdaurora")
                includeGroup("io.github.queerbric")
            }
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        withSourcesJar()
    }
}
