org.gradle.jvmargs=-Xmx2048M

mod_id=spelunkery

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

mod_version=1.21.1-BETA-26.04.05
maven_group=com.ordana.spelunkery

parchment_version = 1.21.1:2024.11.17
quilt_version = 0.20.0-beta.4

fabric_loader_version = 0.16.14
fabric_api_version = 0.116.3+1.21.1

neoforge_version = 21.1.216

modmenu_version = 11.0.3
emi_version = 1.1.22+1.21.1
cloth_version = 15.0.140

moonlight_version = 1.21-2.26.7